### ISSUE TITLE
[feature request] Ability to set `config-path` per mapping

### ISSUE THREAD

**Issue by atmosx** [CircleCI-Public/path-filtering-orb#12]
## Describe Request:

The `config-path` points to a specific file. While the `mapping` section includes multiple modules. Assuming we have a monorepo with different applications, would be nice to set `config-path` per mapping. This way we can split up the configuration to multiple files (e.g. per application). This will ease YAML definition file management considerably and will allow teams to manage their CI files, without risking messing up the company-wide CI.

## Examples:

Here's how the configuration looks now:

```
  gameserver-config:
    jobs:
      - path-filtering/filter:
          config-path: .circle/continue.yaml
          base-revision: "origin/panagiotis/eng-1162-circleci-introduce-path-base-builds"
          mapping: |
            modules/abcd-common gameserver-workflow true
            modules/abcd-common sfu-workflow true
            modules/abcd-game-.* gameserver-workflow true
            modules/abcd-server-common gameserver-workflow true
            modules/abcd-server-common sfu-workflow true
            modules/abcd-video-common sfu-workflow true
            modules/abcd-video-sfu sfu-workflow true
          filters:
            branches:
              only:
                - panagiotis/eng-1162-circleci-introduce-path-base-builds

```

Now definitions for all workflows, need to go to `.circle/continue.yaml`. This creates 1 big complex file that will host build instructions (commands, jobs and workflows) for different applications: sfu, gameserver.

Would be nice to pass `config-path` _per_ mapping, e.g.:

```
  mapping: |
            modules/abcd-common gameserver-workflow  .circle/continue.yaml true
            ...
```

**Comment by karthikmuralidharan** [comment]
It would be huge if we would be able to configure config-path per mapping. Any suggestions on any alternatives for achieving this ?

**Comment by h42zhu** [comment]
This feature should be possible if after the filtering step, there's a `merge-config-files-from-mappings` functionality, and pass the `merged-config-file`, possibly including the merge from the file specified `config-path`, and pass that down to the continuation call.

**Comment by h42zhu** [comment]
@atmosx @karthikmuralidharan This might be possible if we can merge all the config files that have satisfied the mapping conditions into one file, and the `continuation-orb` only accept one config file as input because one pipeline can only have one config attached to it. I'll be working on a tentative solution.

**Comment by h42zhu** [comment]
Update the orb to the latest version, then this feature should be available.
