### ISSUE TITLE
Setup failing to checkout diff

### ISSUE THREAD

**Issue by tiagocborg** [CircleCI-Public/path-filtering-orb#13]
## What happened: Setup failing to checkout diff

This is always failing on circle ci, but it works fine if I run the same command with the same values on my terminal. It is not a new repo. 

If anyone has any idea

```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/home/circleci/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'merge-base', 'main', '58fd9e954ef1dfd9ef8d3782df94a7bb47dbc447']' returned non-zero exit status 128. 
```

**Comment by miqm** [comment]
Same with me, I changed base-revision to `origin/master` and it worked.

**Comment by vlindhol** [comment]
Same here!

**Comment by h42zhu** [comment]
We have not seen the same issue with the newer version of the orb, closing this issue.
