### ISSUE TITLE
Error running Orb on CircleCi Hosted

### ISSUE THREAD

**Issue by pszittyay** [CircleCI-Public/path-filtering-orb#17]
## What happened:
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/home/circleci/.pyenv/versions/3.8.11/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'merge-base', 'main', 'c22bb01717c674fb75ad8d3ebe58de4bbc17a340']' returned non-zero exit status 128.

Exited with code exit status 1

## Expected behavior:

Should continue reading the continue_config.yml and running the corresponding jobs

## Additional Information:
config.yml

version: 2.1
orbs:
  path-filtering: circleci/path-filtering@0.0.3
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:          
          config-path: .circleci/continue-config.yml
          mapping: |
            sgd/backend/.* run-sgd-back true
            sgd/frontend/.* run-sgd-fron true
            trading/app/.* run-nts true

**Comment by dmwelch** [comment]
@pszittyay I'm also having this issue.

**Comment by Markl121** [comment]
The original issue was resolved by:

1. Ensuring a top level `setup:true` is added to the `config.yml`
```
version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.1
```
2. Verifying that there's a detached head or a tangled git tree that could be causing the issue. This could be done duplicating the project into a new repo (one that you can delete later), which would be a new clean repository, preferably with the same project files you are currently using.

**Comment by Markl121** [comment]
I will close this issue on that note, and if there are further concerns, please re-open this issue.
