### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/path-filtering-orb#18]
Add a readme

**Comment by forceedge01** [comment]
+1. If you're going to put the effort in making something for others, makes sense to include a sensible readme in here. The current documentation on the published on circle ci doesn't go on to explain what continue-config is supposed to be. Going all over the place to see how this works, not great.

**Comment by mathaeus** [comment]
Heavy +1 on this one.

@KyleTryon I only figured out how this orb really works by the help of examples of other people like this one: https://gist.github.com/ryanpedersen42/c867acd9b0837789a92836e8f5bd8b55

**Comment by njsaunders** [comment]
+1 - same

**Comment by elliotforbes** [comment]
Closing as the readme has been added.
