### ISSUE TITLE
Include link to Dynamic Configuration documentation

### ISSUE THREAD

**Issue by hud-code** [CircleCI-Public/path-filtering-orb#19]
## Describe Request:
It would be great to get links to the dynamic config documentation for the path-filtering orb 

## Examples:
Dynamic Config: https://circleci.com/docs/2.0/dynamic-config/
Github documentation: https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/setup-workflows.md#concepts

**Comment by Markl121** [comment]
Dynamic config docs link has been added to the [orb docs](https://circleci.com/developer/orbs/orb/circleci/path-filtering) as Homepage in https://github.com/CircleCI-Public/path-filtering-orb/pull/63
