### ISSUE TITLE
Return previous build status result if no changes were detected

### ISSUE THREAD

**Issue by stascnb** [CircleCI-Public/path-filtering-orb#47]
## Describe Request:

If the job has not been run, should still return a success message or inherit from the previous build on the branch

## Examples:

For example lets say i have a mono repo,

And there is
/client
/server

And lets say I have rules on github, so the build for /client and /server has to pass before being merged,

The problem arises if for example I pushed only to /client

Then it returns:
/client - job success
/server - job waiting

It should return a status of the previous recorded build in that branch rather than not triggering a build at all and hanging

## Supporting Documentation Links:

1) https://circleci.com/developer/orbs/orb/circleci/path-filtering

Would also be greatly appreciated if there was a git example outlining a hack or workaround this issue

**Comment by PeterYamamoto** [comment]
^ I am having the same issue

**Comment by stascnb** [comment]
@h42zhu would u have any recommendations for it? :)

**Comment by h42zhu** [comment]
@stascnb Unfortunately this issue cannot solved within this orb, as it doesn't deal with Github status updates. Fundamentally the issue to me seems like how do we handle Github status update on jobs that potentially won't run. It's probably better to raise this issue on https://circleci.canny.io/ to get more visibility.

**Comment by Fernando-Abreu** [comment]
I will close this issue since it's not doable
