### ISSUE TITLE
Diff Not Triggered on Old Merges

### ISSUE THREAD

**Issue by parisholley** [CircleCI-Public/path-filtering-orb#49]
## Orb version:

0.0.2

## What happened:

Given the following git history, if master is forked, then master 1/2/3 runs... when the commit from branch 2 is merged into master 4, the diff logic isn't taking into consideration changes that happened inside branch 2 and won't get triggered on the master 4 build (only the diff between 3/4 is done). 

```
       master 4
      /         \
  master 3      |
     |          |
  master 2   branch 2
     |          |
  master 1   branch 1
      \         /
      old commit
```
## Expected behavior:

I would expect it to detect changes that happened between diverge and merge and run any touched workflows on master 4. as I understand it, the current impl is just using a standard diff to previous commit and supporting this will probably require more complex logic.

**Comment by Fernando-Abreu** [comment]
This problem is too specific, and we won't have enough capacity to work on this. If you want, feel free to open a PR and we will take a look. In the meantime, I'm closing this issue.
