### ISSUE TITLE
Orb gone...?

### ISSUE THREAD

**Issue by arcataroger** [CircleCI-Public/path-filtering-orb#57]
## Orb version:

Any (we're running 0.1.1, but they all seem gone)

## What happened:

Pipelines are getting the error:
![image](https://user-images.githubusercontent.com/11964962/191625709-bca4e131-a215-434f-87b5-b1881ab7da9d.png)

The orb page itself is gone too:
https://circleci.com/developer/orbs/orb/circleci/path-filtering

## Expected behavior:

Orb should be in the registry and pipeline should be able to run.

## Additional Information:

Last archived page: https://web.archive.org/web/20220817062937/https://circleci.com/developer/orbs/orb/circleci/path-filtering

Not sure what is going on here, but the orb seems to be gone altogether...

**Comment by felicianotech** [comment]
There's an active incident: https://status.circleci.com/incidents/7pfbzf4g9dcs

**Comment by arcataroger** [comment]
Thanks, @felicianotech !

**Comment by felicianotech** [comment]
No problem. I'm going to keep this issue open for now in case others come across this with the same concern.

**Comment by arcataroger** [comment]
Closing this because the incident has been resolved. Thanks again!
