### ISSUE TITLE
Make checkout step optional

### ISSUE THREAD

**Issue by adrogon** [CircleCI-Public/path-filtering-orb#59]
## Describe Request:

The [attach_workspace](https://github.com/CircleCI-Public/path-filtering-orb/blob/main/src/jobs/filter.yml#L55) step is currently performed after the `checkout` one.

`attach_workspace` is useful if a previous job contained a `persist_to_workspace` step.
If said job already contained a `checkout` step, the Path Filtering Orb performs a `checkout` for no reason.

Making the `checkout` step of this orb optional through configuration would allow for more use cases; for example, retrieving the repository by attaching the workspace, or restoring a cache.

Thank you.

**Comment by Fernando-Abreu** [comment]
I'm closing this ticket in favour of this one: https://github.com/CircleCI-Public/path-filtering-orb/issues/68
