### ISSUE TITLE
is this repository abandoned?

### ISSUE THREAD

**Issue by glebsts** [CircleCI-Public/path-filtering-orb#60]
Hello,

I can see bunch of opened pull requests in this repo, last commit happened May 19 2022. 
I.e. dependency on continuation orb is too old (it is 0.3.1 now). 
Documentation and examples need some updates (`setup: true`, version bumping etc).

Is this repository maintained, or abandoned? Do you accept new maintainers? 
Tagging last three main branch committers:
@h42zhu @adamdmharvey @sulami  
How are you, guys?

Thanks,

**Comment by adamdmharvey** [comment]
Hi 👋🏻 @glebsts ! No idea if this repo is abandoned; I'm just an open source contributor, like yourself, who had one of my PRs merged in back in March 2022 by the maintainers.

Being in this org infers it's still fully owned by CircleCI themselves, and the person who merged my PR was @EricRibeiro (who you can see via their profile is a CircleCI employee).  Maybe they have ideas?

**Comment by h42zhu** [comment]
Hi @glebsts , really sorry about this, for various reasons this repository was not properly taken care of during the past year. 
We're sorting through some priorities, and while I don't have any exact timing on hand, we will start clean up and maintain this repository soon-ish.

**Comment by elliotforbes** [comment]
Closing for now - we are in the process of prioritising the outstanding work for the open PRs in this repo.
