### ISSUE TITLE
Dynamic base-revision possible?

### ISSUE THREAD

**Issue by benjaoming** [CircleCI-Public/path-filtering-orb#65]
## Describe Request:

Let's say we have path-filtering in order to save some builds. I suppose this is normal.

But what if we are working on `feature-branch` and everything has changed compared to `main`?

Is there a way to retrieve the target branch of a PR and use this dynamically?

## Examples:

PR targeting `develop` should have `base-revision: develop` but a PR targeting `main` should keep `base-revision: main`

## Supporting Documentation Links:

https://circleci.com/docs/pipeline-variables/ doesn't seem to have PR target branch as a parameter.

**Comment by h42zhu** [comment]
This issue thread may provide the solution to what you're looking for:

https://github.com/CircleCI-Public/path-filtering-orb/issues/7

**Comment by benjaoming** [comment]
Thanks! It's weird that the issue was closed because "it isn't possible at this time"

I'll try out a variation of [this workaround](https://github.com/CircleCI-Public/path-filtering-orb/issues/7#issuecomment-880563553).

**Comment by benjaoming** [comment]
[The workarounds](https://github.com/CircleCI-Public/path-filtering-orb/issues/7#issuecomment-880563553) do not match my intention. I want to compare with the target branch of a Pull Request.

Many projects have several long-lived branches, `main`, `develop`, `1.x`, `staging` etc.

`pipeline.git.branch`:

> The name of the git branch that was pushed to trigger the pipeline.

`pipeline.git.base_revision`:

> The long (40-character) git SHA of the build prior to the one being built. Note: While in most cases pipeline.git.base_revision will be the SHA of the pipeline that ran before your currently running pipeline, there are some caveats. When the build is the first build for a branch, the variable will not be present. In addition, if the build was triggered via the API, the variable will not be present.

**Comment by benjaoming** [comment]
@ValentinCondurache no, unfortunately not. I'm thinking to accept that the situation is that we cannot do conditional builds in a perfect manner. I think it could be possible to have a 2-step continuation pattern where the first step would contain some custom code to detect the PR's target branch (the code that needs to be in path-filtering-orb!) and then launch the continuation orb from there with some `pr_target_branch` parameter set...

But I don't really want to build features like this. I recall that this was possible in Jenkins. I don't see that GitHub Actions support it: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
I don't understand why. If we want to create conditional build logic, we need to be able to express the logic the right way so we can go and say "I managed to save build time without compromising test coverage" etc.

And this Circle CI Orb did the first part of the work, making the base-branch configurable. It's just so little left :)

**Comment by benjaoming** [comment]
@h42zhu yes, it would definitely be nice to have the `pr_target_branch` at hand in general!

**Comment by ValentinCondurache** [comment]
@h42zhu I also think would be a helpful parameter to have 👍

**Comment by benjaoming** [comment]
@h42zhu I know this is the wrong place to mention this, but where ever you have requested a new parameter for the PR target, I have another scenario that can be added in the request: I would like this feature for CI checks like `pre-commit --from-ref main --to-ref HEAD`.

If you aren't familiar with pre-commit: The command will verify that everything in a build commit "lints" according to whatever has changed compared to the `main` branch. The problem? Again, `main` is hard-coded and this assumption breaks when we are targeting PR builds at other branches.

There may be other approaches to linting, I'm sure. This is just to illustrate a different use-case that can benefit from the exact same parameter.

**Comment by Coconutcoo** [comment]
Just chiming in to add this is a feature we could do with too. Has there been any progress getting a `pr_target_branch` or similar pipeline variable available?

Right now we're still using a complex bash script that triggers the API to start the rest of the workflows that we'd like to get rid of, but this issue is a real pain for us as we build on staging & main.

For our use case, and possibly others, we could just duplicate the path-filtering/filter job, but add one of the snippets below (with appropriate branch names in the filter and the base-revision) for each one. Still, it's a lot of repeated code in the config file that we could avoid with just one pipeline variable!
```
filters: 
  branches:
    only:
      -main
```

**Comment by Fernando-Abreu** [comment]
I'm closing this as this issue cannot be directly solved within this orb. Feel free to upvote this canny: https://circleci.canny.io/cloud-feature-requests/p/provide-env-variable-for-branch-name-targeted-by-pull-request
